### ISSUE TITLE
In Lesson mode, enable highlighting code segments

### ISSUE THREAD

**Issue by gabrielflorit** [script-8/script-8.github.io#125]

**Comment by grantlouisherman** [comment]
For this one would you want it to be like a normal code editor?

**Comment by gabrielflorit** [comment]
I'd like to be able to specify a line range to highlight. For example, in the lessons file (https://github.com/script-8/script-8.github.io/blob/dev/src/utils/lessons.yaml) I set what lines to add or modify in the next slide. And I'd like to be able to visually remind users where to look at. Ideally codemirror allows us to highlight a line range.

**Comment by grantlouisherman** [comment]
Would you want to highlight something like this?
<img width="416" alt="screen shot 2019-02-05 at 4 36 50 pm" src="https://user-images.githubusercontent.com/5606705/52313693-4c97dc80-2964-11e9-9f9d-8a48d6371c8f.png">

**Comment by grantlouisherman** [comment]
Or would it be more ad-hoc than that?

**Comment by gabrielflorit** [comment]
I think we want the ability to highlight any given range of text already present in the codemirror instance.

**Comment by grantlouisherman** [comment]
So I think there is a way to do that with this:
> doc.getRange(from: {line, ch}, to: {line, ch}, ?separator: string) → string
Get the text between the given points in the editor, which should be {line, ch} objects. An optional third argument can be given to indicate the line separator string to use (defaults to "\n").

What I am confused by is how are you generating those ranges?

**Comment by grantlouisherman** [comment]
Okay that makes a bit more sense. So you would want to highlighted text something like this: 
<img width="85" alt="screen shot 2019-02-06 at 9 30 44 am" src="https://user-images.githubusercontent.com/5606705/52361707-b3b0a200-29f3-11e9-9fb3-bf2bfe0d9812.png"> within the text? Just because right now I see that you have the code mirror object setup, so I want to just understand your definition of _highlighting._  I apologize for my ignorance I am just trying to get a clear understanding of what you were thinking about.  💯

**Comment by gabrielflorit** [comment]
No apologies necessary!

By highlighting I mean something where the reader's attention is diverted to. So it could be something like this:
<img width="523" alt="screenshot 2019-02-06 17 23 11" src="https://user-images.githubusercontent.com/370976/52377816-fd20e180-2a33-11e9-98cd-0ed03530b9c3.png">

Something that lets the reader know where to look at - what lines we are talking about in this current lesson slide.

**Comment by gabrielflorit** [comment]
And of course this also goes hand-in-hand with the other codemirror issue, the one about moving to a specific line.

**Comment by grantlouisherman** [comment]
I just wanted to give you an update, So I think there is a way with this:

> cm.addOverlay(mode: string|object, ?options: object)
Enable a highlighting overlay. This is a stateless mini-mode that can be used to add extra highlighting. For example, the search addon uses it to highlight the term that's currently being searched. mode can be a mode spec or a mode object (an object with a token method). The options parameter is optional. If given, it should be an object, optionally containing the following options:
opaque: bool
Defaults to off, but can be given to allow the overlay styling, when not null, to override the styling of the base mode entirely, instead of the two being applied together.
priority: number
Determines the ordering in which the overlays are applied. Those with high priority are applied after those with lower priority, and able to override the opaqueness of the ones that come before. Defaults to 0.

Looking into it now.

**Comment by gabrielflorit** [comment]
Oh that's interesting, good find.

**Comment by grantlouisherman** [comment]
Hey @gabrielflorit so I have a solution locally that seems to be working. My question to you is how do you want to assign the line to the function? We can add it to the yaml for each lesson? Just want to get your take. 
<img width="626" alt="screen shot 2019-02-12 at 4 37 28 pm" src="https://user-images.githubusercontent.com/5606705/52677928-b411d700-2ee4-11e9-8da1-4774e9e5e94b.png">

**Comment by gabrielflorit** [comment]
Cool!!!!

I think for now assume it comes from the yaml. I might figure out an easier
way later.

**Comment by grantlouisherman** [comment]
Okay so how do you want to do it? I put a PR for the function and you add the line in the yaml? Or I do a setup of having the line in the yaml and the function and you can take it from there?

**Comment by gabrielflorit** [comment]
Good question. How about you add a couple of test lines in the yaml and submit a PR? and then I'll take it from there.

**Comment by grantlouisherman** [comment]
https://github.com/script-8/script-8.github.io/pull/192/files

**Comment by grantlouisherman** [comment]
Let me know what you think @gabrielflorit

**Comment by gabrielflorit** [comment]
closed by PR and https://github.com/script-8/script-8.github.io/commit/f2e46b2600a438d815dd9dfeaa6a22591e2d4c72
