### ISSUE TITLE
Add ability to export game as standalone html file

### ISSUE THREAD

**Issue by gabrielflorit** [script-8/script-8.github.io#175]

**Comment by Kethku** [comment]
Can you talk a little bit about how you were thinking of doing this? I would really like to embed the game into my blog but I can't really as things currently are. Maybe I could help push this forward?

**Comment by gabrielflorit** [comment]
The absolute easiest way is to give readers an `<iframe />` embed tag. And I think that's probably not a lot of work. But it does mean they are not hosting the game on their pages.

Some more thoughts, in no particular order:

- can `index.html` should contain all the code? i.e. you don't need a connection if you have the `index.html`.
- the APIs are still in flux. we should avoid maintaining two versions - one for the full FC, one for embed.
- running an embedded game should increment game counters.

**Comment by Kethku** [comment]
Good points. I am concerned about the fact that APIs are still in flux. What happens if a post is written that depends on old APIs and embeds the current version of the game. Embedded games will fail in weird ways. pico-8's strategy seems to be export an entire copy of the engine so that the embedded game doesn't depend on future changes. This strikes me as much harder though...

**Comment by gabrielflorit** [comment]
Good point. This requires some further thinking.

**Comment by gabrielflorit** [comment]
Done mostly by https://github.com/script-8/script-8.github.io/commit/ab2a65ec7aa8065e442637e93a5a19df063df1cb
